# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_email', models.TextField()),
                ('li_first_name', models.CharField(max_length=50)),
                ('li_last_name', models.CharField(max_length=50)),
                ('li_picture_url', models.URLField()),
                ('li_profile_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
